name: "Claude PR Composite Action"
description: "Run Claude Code on pull requests or issues when @claude is mentioned"

inputs:
  trigger_phrase:
    description: "The phrase that triggers the action"
    required: true
  timeout_minutes:
    description: "How many minutes to wait before timing out"
    required: true
  github_token:
    description: "Token for calling the GitHub API"
    required: true
  use_bedrock:
    description: "Whether to use AWS Bedrock"
    required: true
  model:
    description: "Which Claude model to use"
    required: true
  app_id:
    description: "GitHub App ID"
    required: true
  app_private_key:
    description: "GitHub App private key"
    required: true
  aws_role_to_assume:
    description: "AWS Role to assume for Bedrock"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate GitHub App token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.app_private_key }}


    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role_to_assume }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Run Claude Code
      uses: ./.github/workflows/claude-pr-action.yml
      with:
        trigger_phrase: ${{ inputs.trigger_phrase }}
        timeout_minutes: ${{ inputs.timeout_minutes }}
        github_token: ${{ inputs.github_token }}
        use_bedrock: ${{ inputs.use_bedrock }}
        model: ${{ inputs.model }}
