name: Claude PR Action

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

on:
  # issue_comment:
  #   types: [created]
  # pull_request_review_comment:
  #   types: [created]
  # issues:
  #   types: [opened, assigned]
  #   branches: [fix/signup-redirect-issue]
  # pull_request:
  #   types: [opened, assigned]
  #   branches: [fix/signup-redirect-issue]
  push:
    branches: [fix/signup-redirect-issue]
jobs:
  claude-pr:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1       
    steps:
      - name: Call Claude PR Composite Action
        uses: ./.github/actions/claude-pr-action/action.yml
        with:
          trigger_phrase: "@claude"
          timeout_minutes: "60"
          github_token: ${{ steps.app-token.outputs.token }}
          use_bedrock: "true"
          model: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
